default: &default
  adapter: <%= adapter %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= databaseName %>_development
  username: <%= databaseUsername %>
  password: <%= databasePassword %>
  host: <%= databaseHost %>
  port: <%= databasePort %>

test:
  <<: *default
  database: <%= databaseName %>_test
  username: <%= databaseUsername %>
  password: <%= databasePassword %>
  host: <%= databaseHost %>
  port: <%= databasePort %>

production:
  <<: *default
  database: <%= databaseName %>_production
  username: <%= databaseUsername %>
  password: <%= databasePassword %>
  host: <%= databaseHost %>
  port: <%= databasePort %>